Added forms page and roster
pdxtroop150/troop150-website pull request #30
Opened 2024-09-24 02:58 UTC by KrispyKiwi315

^

2024-09-24 03:04 UTC, readerkid approved these changes

2024-09-24 03:30 UTC, txase requested changes

2024-09-24 03:30 UTC, txase commented on src/content/pages/forms.md
> +#### [Reimbursement Form](https://form.jotform.com/Troop150/troop-150-reimbursement-form)
I think we should put this at the bottom of the list. I think the health forms are more commonly used by troop members.

2024-09-24 03:30 UTC, txase commented on src/content/pages/forms.md
> +No reimbursements will be paid or credited until the trip leader submits a complte "Event Recap Sheet". If you do not have a copy of the excel from, email Treasurer@Troop150.org for a copy.  Note if
Typo: "complte" -> "completed"

2024-09-24 03:30 UTC, txase commented on src/content/pages/forms.md
> +#### [Reimbursement Form](https://form.jotform.com/Troop150/troop-150-reimbursement-form)
Let's figure out if there's a way to be more clear on what is a link (vs a section header).

2024-10-01 02:26 UTC, txase approved these changes
📋

2024-10-01 02:27 UTC, merged